version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./chainbridge-runtime-config.js:/usr/share/nginx/html/chainbridge-runtime-config.js
    ports:
      - "3000:80"
